### PR TITLE
Create default.php

### PR DESCRIPTION
**Pull request by dgramop**
Hello! This is my first pull to this repo!
A couple things
1. I changed some of the format of the code, don't worry though:
2. This should be the only page on the site that will use fullpage.js (though other pages will use materialize and scrollreveal)
3. I would also like to request to change the css llibrary from bootstrap to materialize. I would also like to use CDN for everything (it might be faster)

### CODE REVIEW

**Comment by dgramop** [comment]
Hold on, forgot an edit!

**Comment by ApolloZhu** [comment]
You can always commit after creating the pull request, the changes can be merged together

**Comment by dgramop** [comment]
Done

**Comment by dgramop** [comment]
You can merge now if needed
Thanks!

**Comment by dgramop** [comment]
We should change the title to index.html to make it active. Ill write a JS only system (AJAX based) for the notifications later on. Ill also use the browser native notification, as it is a bit better than the bootstrap plugin.

**Comment by dgramop** [comment]
Once the new notification thing is done (and a few more features are added) then we can deploy this by renaming.

**Comment by ApolloZhu** [comment]
True. Just modifying `default.html` to include more actual information. Can you work on the notification part?

**Comment by dgramop** [comment]
I will, a bit busy rn tho

**Comment by dgramop** [comment]
I did leave a few things blank on default for you to fill in

**Comment by ApolloZhu** [comment]
True

**Pull request merged**
