### PR TITLE
Format default.php

### PR DESCRIPTION
**Pull request by ApolloZhu**
## default.php
- Correct Indentation
- Move all script to end of body
- Change logic of setting `title`
## Other
- Description of `php` usage
- Adding License of **aGRAMOP**
- Moving Contribution Information to another file for later use

### CODE REVIEW

**Comment by ApolloZhu** [comment]
@BrainyBrian  Do you have any complains?

**Comment by dgramop** [comment]
If you need, you can change the name default.php to .html, we can change it back when we migrate

**Comment by dgramop** [comment]
Sounds great! You kinda overdid the title logic, that was necessary, but hey, it doesn't hurt. 👍 💯

**Comment by dgramop** [comment]
😄

**Pull request merged**
