### PR TITLE
More updates coming to fit material guidlines

### PR DESCRIPTION
**Pull request by dgramop**

### CODE REVIEW

**Comment by ApolloZhu** [comment]
Is there any reason why Atom is so special? And how is that material?

**Comment by dgramop** [comment]
AtomIDE is special because: 
-Open source
-Modular (I think)
-Cross-platform (Any more cross-platform and will start supporting 
-Lightweight (unlike eclipse or something)
-Free
-Made by GitHub

Material is special because specs are made by google
https://material.google.com/
Watch the videos that they made.

**Comment by ApolloZhu** [comment]
Then Visual Studio Code is pretty much the same, except that it is made by Microsoft...
Choose a more related title for your commit next time. Seems that Atom has nothing to do with material...

**Comment by dgramop** [comment]
Atom has nothing to do with material, correct. Sorry if i confused you

**Comment by dgramop** [comment]
By the way, the structure has to be changed to fit Material guidlines

**Pull request closed without merging**
